### ISSUE TITLE
Replace RSpec with MiniTest:Spec

### ISSUE THREAD

**Issue by liveh2o** [liveh2o/protobuf-activerecord#9]
RSpec is nice, but MiniTest is more lightweight and with MiniTest::Spec, similar (if not the same) syntax can be supported. Replacing shouldn't be terribly difficult (famous last words).

**Comment by film42** [comment]
@liveh2o Is this still something you're interested in seeing happen?

**Comment by liveh2o** [comment]
Sure. @decriptor started a PR for this (#10), but it seems to have fizzled. If you want to run with it, that would be great.

**Comment by liveh2o** [comment]
There isn't a lot of value in changing the specs at this point. Closing.
